version: '3.7'

services:
  database:
    image: postgres
    container_name: database_my_blog
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=mublog
      - POSTGRES_DB=mublog
